name: geoanywhere
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.3.0
  flutter_animate: ^4.5.2
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3
  flutter_secure_storage: ^9.2.4
  sqflite: ^2.3.2
  path_provider: ^2.1.5
  geolocator: ^13.0.2
  device_info_plus: ^11.3.0
  share_plus: ^10.1.4
  connectivity_plus: ^6.1.3
  vibration: ^3.1.3
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.3.1
  flutter_inappwebview: ^6.1.5
  package_info_plus: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
